apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      server: db
  template:
    metadata:
      name: db-noticias
      labels:
        server: db
    spec:
      containers:
        - name: db-noticias-container
          image: aluracursos/mysql-db:1
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.3"
              memory: "512Mi"
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-vol
          envFrom:
            - configMapRef:
                name: db-configmap
      volumes:
        - name: mysql-vol
          hostPath:
            path: /data/mysql
            type: DirectoryOrCreate
