apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: portal-noticias-replicasets
spec:
  replicas: 1
  selector:
    matchLabels:
      "app": "portal"
  template:
    metadata:
      name: portal-noticias
      labels:
        "app": "portal"
    spec:
      containers:
        - name: portal-noticias
          image: aluracursos/portal-noticias:1
          resources:
            limits:
              cpu: "0.4"
              memory: "256Mi"
            requests:
              cpu: "0.2"
              memory: "128Mi"
          envFrom:
            - configMapRef:
                name: portal-configmap
