apiVersion: v1
kind: Pod
metadata:
  name: portal-noticias
  labels:
    "app": "portal"
spec:
  containers:
    - name: portal-noticias
      image: aluracursos/portal-noticias:1
      resources:
        limits:
          cpu: "0.75"
          memory: "256Mi"
        requests:
          cpu: "0.5"
          memory: "128Mi"
      envFrom:
        - configMapRef:
            name: portal-configmap
